version: "3.8"

services:
  postgres:
    container_name: "${PG_CONTAINER_NAME}"
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  pgadmin:
    container_name: "${PGADMIN_CONTAINER_NAME}"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - 5050:80

volumes:
  pgdata:
