"""change column worker to processed_by

Revision ID: 477390ebc706
Revises: ca139d6c7889
Create Date: 2021-10-27 16:19:15.998289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477390ebc706'
down_revision = 'ca139d6c7889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
